id: A9FCF1854
title: Great Clouds of First-Portion Offerings for Prosperity
type: translation
pechas:
- IB2A520AA
- IF0554377
- I372CD1AE
- I4A40B15B
- I391131BF
source_metadata:
  languages:
  - en
  - es
  - fr
  - nl
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:07:34.876430
  last_modified_at: 2023-01-04 13:07:34.876437
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  IB2A520AA/A185: 1C26
  IF0554377/C63F: 1C26
  I372CD1AE/1FBB: 1C26
  I4A40B15B/1B19: 1C26
  I391131BF/93C4: 1C26
